import type { AgentCommand, SlashCommandItem } from './types.js';

export const CLAUDE_COMMANDS: SlashCommandItem[] = [
  {
    command: '/compact',
    label: 'Compact context',
    description: 'Summarize past conversation turns into a lean checkpoint to free context',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'archive',
    actionType: 'immediate',
  },
  {
    command: '/review',
    label: 'Review code or PR',
    description: 'Inspect git diff and review pending changes against best practices',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'search',
    actionType: 'insert',
    hint: '[pr-number or branch]',
  },
  {
    command: '/pr',
    label: 'Create pull request',
    description: 'Draft PR summary, test notes, and submit a pull request for branch changes',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'branch',
    actionType: 'insert',
    hint: '[title]',
  },
  {
    command: '/cost',
    label: 'Token usage and cost',
    description: 'Display token consumption metrics and estimated API spend for this session',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'chart',
    actionType: 'immediate',
  },
  {
    command: '/doctor',
    label: 'Health check',
    description: 'Check environment health, verify tool paths, and validate config',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'shield',
    actionType: 'insert',
  },
  {
    command: '/init',
    label: 'Initialize CLAUDE.md',
    description: 'Scan repository structure and generate or refresh project guidelines (CLAUDE.md)',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'fileEdit',
    actionType: 'insert',
  },
  {
    command: '/bug',
    label: 'Report a bug',
    description: 'Report an issue or unexpected behavior directly to Anthropic',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'alert',
    actionType: 'insert',
    hint: '[description]',
  },
  {
    command: '/clear',
    label: 'Clear conversation',
    description: 'Reset conversation context and start a clean slate for upcoming prompts',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'refresh',
    actionType: 'immediate',
  },
  {
    command: '/terminal-setup',
    label: 'Terminal keybindings',
    description: 'Configure shell completion, shortcuts, and terminal integration',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'settings',
    actionType: 'insert',
  },
  {
    command: '/help',
    label: 'Claude help',
    description: 'Show Claude Code documentation, built-in features, and command reference',
    category: 'agent',
    agentIds: ['claude'],
    icon: 'help',
    actionType: 'insert',
  },
];

export const CODEX_COMMANDS: SlashCommandItem[] = [
  {
    command: '/compact',
    label: 'Compact context',
    description: 'Compact active conversation turns into a summary to conserve context tokens',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'archive',
    actionType: 'immediate',
  },
  {
    command: '/diff',
    label: 'View git diff',
    description: 'Review git modifications and unstaged changes generated by Codex',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'diff',
    actionType: 'insert',
  },
  {
    command: '/approval',
    label: 'Approval mode',
    description: 'Toggle auto-approval for command execution and filesystem edits',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'zap',
    actionType: 'immediate',
  },
  {
    command: '/model',
    label: 'Switch model',
    description: 'Switch between Codex models (e.g. 6-luna, 5.6-terra, o3-mini, gpt-4o)',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'brain',
    actionType: 'immediate',
  },
  {
    command: '/undo',
    label: 'Undo last turn',
    description: 'Revert the last prompt or tool modification in this session',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'undo',
    actionType: 'immediate',
  },
  {
    command: '/clear',
    label: 'Clear session memory',
    description: 'Wipe current context window and restart cleanly',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'refresh',
    actionType: 'immediate',
  },
  {
    command: '/help',
    label: 'Codex CLI reference',
    description: 'View Codex keyboard shortcuts, execution flags, and command reference',
    category: 'agent',
    agentIds: ['codex'],
    icon: 'help',
    actionType: 'insert',
  },
];

export const ANTIGRAVITY_COMMANDS: SlashCommandItem[] = [
  {
    command: '/goal',
    label: 'Autonomous goal mode',
    description: 'Run extra-thorough autonomous execution that continues until the goal is fully verified',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'circleDot',
    actionType: 'insert',
    hint: '[task description]',
  },
  {
    command: '/plan',
    label: 'Architecture plan',
    description: 'Create an interactive step-by-step implementation plan before modifying code',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'list',
    actionType: 'insert',
    hint: '[task description]',
  },
  {
    command: '/grill-me',
    label: 'Alignment interview',
    description: 'Run an interactive interview to probe requirements, edge cases, and design trade-offs',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'message',
    actionType: 'insert',
  },
  {
    command: '/browser',
    label: 'Web and docs browser',
    description: 'Delegate live web browsing, documentation scraping, or web application testing',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'globe',
    actionType: 'insert',
    hint: '[url or search query]',
  },
  {
    command: '/learn',
    label: 'Save skill or rule',
    description: 'Save corrected behavior, project guidelines, or reusable workflow into persistent rules',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'sparkles',
    actionType: 'insert',
    hint: '[rule or convention]',
  },
  {
    command: '/boost',
    label: 'Boosted reasoning',
    description: 'Engage multi-perspective strategic reasoning, verification checks, and plan critique',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'zap',
    actionType: 'insert',
  },
  {
    command: '/compact',
    label: 'Compact context',
    description: 'Distill earlier verbose tool outputs and thoughts into a clean summary checkpoint',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'archive',
    actionType: 'immediate',
  },
  {
    command: '/clear',
    label: 'Clear memory',
    description: 'Reset conversational context and start afresh',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'refresh',
    actionType: 'immediate',
  },
  {
    command: '/help',
    label: 'Antigravity guide',
    description: 'Browse Antigravity skills, SDK methods, and slash command reference',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: 'help',
    actionType: 'insert',
  },
];

export const TERMINAL_UNIVERSAL_COMMANDS: SlashCommandItem[] = [
  {
    command: '/switch',
    label: 'Switch agent or model',
    description: 'Switch active agent (Claude, Codex, Antigravity) with context handoff',
    category: 'terminal',
    icon: 'swap',
    actionType: 'immediate',
  },
  {
    command: '/undo',
    label: 'Undo last turn',
    description: 'Revert the last user message and agent response',
    category: 'terminal',
    icon: 'undo',
    actionType: 'immediate',
  },
  {
    command: '/compact',
    label: 'Compact history',
    description: 'Compact conversation into a lean checkpoint to optimize token usage',
    category: 'terminal',
    icon: 'archive',
    actionType: 'immediate',
  },
  {
    command: '/stop',
    label: 'Stop agent or turn',
    description: 'Stop active turn generation or park underlying subprocess to free RAM & CPU',
    category: 'terminal',
    icon: 'stop',
    actionType: 'immediate',
  },
  {
    command: '/auto',
    label: 'Toggle auto-approve',
    description: 'Toggle automatic approval for all tool and shell command requests',
    category: 'terminal',
    icon: 'zap',
    actionType: 'immediate',
  },
  {
    command: '/mcp',
    label: 'MCP servers and plugins',
    description: 'Add, test and turn MCP servers on or off, and see each agent\'s plugins and skills',
    category: 'terminal',
    icon: 'plug',
    actionType: 'immediate',
  },
  {
    command: '/stats',
    label: 'Vendor limits and usage',
    description: 'View 5-hour & weekly token utilization, rate limit resets, and subscription status',
    category: 'terminal',
    icon: 'card',
    actionType: 'immediate',
  },
  {
    command: '/git',
    label: 'Git status and diff',
    description: 'Ask agent to inspect current repository git branch, status, and modified files',
    category: 'terminal',
    icon: 'commit',
    actionType: 'insert',
  },
];

/**
 * The commands and skills the agent reported, in its order. A plugin's own are named
 * "<plugin>:<name>" and MCP prompts "mcp:<server>:<name>"; the prefix is shown as the source.
 */
export function agentReportedCommands(reported: AgentCommand[], known: SlashCommandItem[] = []): SlashCommandItem[] {
  const icons = new Map(known.map((k) => [k.command, k.icon]));
  return reported.map((c) => {
    const cut = c.name.lastIndexOf(':');
    const source = c.name.startsWith('mcp:') ? 'MCP' : cut > 0 ? c.name.slice(0, cut) : undefined;
    const command = `/${c.name}`;
    return {
      command,
      label: cut > 0 ? c.name.slice(cut + 1) : c.name,
      description: c.description,
      category: 'agent',
      hint: c.hint,
      icon: icons.get(command),
      actionType: 'insert',
      source,
      fromAgent: true,
    };
  });
}

/**
 * Get all available slash commands for a specific agent.
 * Combines the agent's native commands (what it reported, else a built-in list) with
 * universal terminal session commands.
 */
export function getSlashCommandsForAgent(agentId?: string, reported?: AgentCommand[]): SlashCommandItem[] {
  const normId = (agentId || '').toLowerCase();

  let agentCommands: SlashCommandItem[] = [];
  if (reported && reported.length > 0) {
    agentCommands = agentReportedCommands(reported, [...CLAUDE_COMMANDS, ...CODEX_COMMANDS, ...ANTIGRAVITY_COMMANDS]);
  } else if (normId.includes('claude') || normId.includes('anthropic')) {
    agentCommands = CLAUDE_COMMANDS;
  } else if (normId.includes('codex') || normId.includes('openai')) {
    agentCommands = CODEX_COMMANDS;
  } else if (normId.includes('antigravity') || normId.includes('gemini') || normId.includes('google')) {
    agentCommands = ANTIGRAVITY_COMMANDS;
  } else {
    // Default / Mock agent
    agentCommands = [
      {
        command: '/compact',
        label: 'Compact context',
        description: 'Compact earlier verbose turns into a clean summary checkpoint',
        category: 'agent',
        icon: 'archive',
        actionType: 'immediate',
      },
      {
        command: '/clear',
        label: 'Clear memory',
        description: 'Reset context window',
        category: 'agent',
        icon: 'refresh',
        actionType: 'immediate',
      },
      {
        command: '/help',
        label: 'Agent reference',
        description: 'Show agent capabilities and supported tools',
        category: 'agent',
        icon: 'help',
        actionType: 'insert',
      },
    ];
  }

  // Filter out any duplicates from terminal commands that share the same command name
  const agentCommandNames = new Set(agentCommands.map((c) => c.command));
  const uniqueTerminalCommands = TERMINAL_UNIVERSAL_COMMANDS.filter((tc) => !agentCommandNames.has(tc.command));

  return [...agentCommands, ...uniqueTerminalCommands];
}

/**
 * Filter slash commands by user query (e.g. "/co", "rev", "undo")
 */
export function filterSlashCommands(commands: SlashCommandItem[], query: string): SlashCommandItem[] {
  const clean = query.trim().toLowerCase().replace(/^\//, '');
  if (!clean) return commands;

  return commands.filter((cmd) => {
    const cmdName = cmd.command.toLowerCase().replace(/^\//, '');
    const label = cmd.label.toLowerCase();
    const desc = cmd.description.toLowerCase();
    const source = (cmd.source || '').toLowerCase();
    return cmdName.includes(clean) || label.includes(clean) || desc.includes(clean) || source.includes(clean);
  });
}
