import type { SlashCommandItem } from './types.js';

export const CLAUDE_COMMANDS: SlashCommandItem[] = [
  {
    command: '/compact',
    label: 'Compact Context',
    description: 'Summarize past conversation turns into a lean checkpoint to free context',
    category: 'agent',
    agentIds: ['claude'],
    icon: '📦',
    actionType: 'immediate',
  },
  {
    command: '/review',
    label: 'Review Code / PR',
    description: 'Inspect git diff and review pending changes against best practices',
    category: 'agent',
    agentIds: ['claude'],
    icon: '🔍',
    actionType: 'insert',
    hint: '[pr-number or branch]',
  },
  {
    command: '/pr',
    label: 'Create Pull Request',
    description: 'Draft PR summary, test notes, and submit a pull request for branch changes',
    category: 'agent',
    agentIds: ['claude'],
    icon: '🚀',
    actionType: 'insert',
    hint: '[title]',
  },
  {
    command: '/cost',
    label: 'Token Usage & Cost',
    description: 'Display token consumption metrics and estimated API spend for this session',
    category: 'agent',
    agentIds: ['claude'],
    icon: '📊',
    actionType: 'immediate',
  },
  {
    command: '/doctor',
    label: 'Health & Diagnostics',
    description: 'Check environment health, verify tool paths, and validate config',
    category: 'agent',
    agentIds: ['claude'],
    icon: '🩺',
    actionType: 'insert',
  },
  {
    command: '/init',
    label: 'Initialize CLAUDE.md',
    description: 'Scan repository structure and generate or refresh project guidelines (CLAUDE.md)',
    category: 'agent',
    agentIds: ['claude'],
    icon: '📝',
    actionType: 'insert',
  },
  {
    command: '/bug',
    label: 'Report a Bug',
    description: 'Report an issue or unexpected behavior directly to Anthropic',
    category: 'agent',
    agentIds: ['claude'],
    icon: '🐛',
    actionType: 'insert',
    hint: '[description]',
  },
  {
    command: '/clear',
    label: 'Clear Conversation',
    description: 'Reset conversation context and start a clean slate for upcoming prompts',
    category: 'agent',
    agentIds: ['claude'],
    icon: '🧹',
    actionType: 'immediate',
  },
  {
    command: '/terminal-setup',
    label: 'Terminal Keybindings',
    description: 'Configure shell completion, shortcuts, and terminal integration',
    category: 'agent',
    agentIds: ['claude'],
    icon: '⚙️',
    actionType: 'insert',
  },
  {
    command: '/help',
    label: 'Claude Help',
    description: 'Show Claude Code documentation, built-in features, and command reference',
    category: 'agent',
    agentIds: ['claude'],
    icon: '❓',
    actionType: 'insert',
  },
];

export const CODEX_COMMANDS: SlashCommandItem[] = [
  {
    command: '/compact',
    label: 'Compact Context',
    description: 'Compact active conversation turns into a summary to conserve context tokens',
    category: 'agent',
    agentIds: ['codex'],
    icon: '📦',
    actionType: 'immediate',
  },
  {
    command: '/diff',
    label: 'View Git Diff',
    description: 'Review git modifications and unstaged changes generated by Codex',
    category: 'agent',
    agentIds: ['codex'],
    icon: '📄',
    actionType: 'insert',
  },
  {
    command: '/approval',
    label: 'Approval Mode',
    description: 'Toggle auto-approval for command execution and filesystem edits',
    category: 'agent',
    agentIds: ['codex'],
    icon: '⚡',
    actionType: 'immediate',
  },
  {
    command: '/model',
    label: 'Switch Model',
    description: 'Switch between Codex models (e.g. 6-luna, 5.6-terra, o3-mini, gpt-4o)',
    category: 'agent',
    agentIds: ['codex'],
    icon: '🧠',
    actionType: 'immediate',
  },
  {
    command: '/undo',
    label: 'Undo Last Turn',
    description: 'Revert the last prompt or tool modification in this session',
    category: 'agent',
    agentIds: ['codex'],
    icon: '↩️',
    actionType: 'immediate',
  },
  {
    command: '/clear',
    label: 'Clear Session Memory',
    description: 'Wipe current context window and restart cleanly',
    category: 'agent',
    agentIds: ['codex'],
    icon: '🧹',
    actionType: 'immediate',
  },
  {
    command: '/help',
    label: 'Codex CLI Reference',
    description: 'View Codex keyboard shortcuts, execution flags, and command reference',
    category: 'agent',
    agentIds: ['codex'],
    icon: '❓',
    actionType: 'insert',
  },
];

export const ANTIGRAVITY_COMMANDS: SlashCommandItem[] = [
  {
    command: '/goal',
    label: 'Autonomous Goal Mode',
    description: 'Run extra-thorough autonomous execution that continues until the goal is fully verified',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '🎯',
    actionType: 'insert',
    hint: '[task description]',
  },
  {
    command: '/plan',
    label: 'Architecture Plan',
    description: 'Create an interactive step-by-step implementation plan before modifying code',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '📋',
    actionType: 'insert',
    hint: '[task description]',
  },
  {
    command: '/grill-me',
    label: 'Alignment Interview',
    description: 'Run an interactive interview to probe requirements, edge cases, and design trade-offs',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '🎙️',
    actionType: 'insert',
  },
  {
    command: '/browser',
    label: 'Web & Documentation Browser',
    description: 'Delegate live web browsing, documentation scraping, or web application testing',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '🌐',
    actionType: 'insert',
    hint: '[url or search query]',
  },
  {
    command: '/learn',
    label: 'Save Skill / Rule',
    description: 'Save corrected behavior, project guidelines, or reusable workflow into persistent rules',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '💡',
    actionType: 'insert',
    hint: '[rule or convention]',
  },
  {
    command: '/boost',
    label: 'Boosted Reasoning',
    description: 'Engage multi-perspective strategic reasoning, verification checks, and plan critique',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '🚀',
    actionType: 'insert',
  },
  {
    command: '/compact',
    label: 'Compact Context',
    description: 'Distill earlier verbose tool outputs and thoughts into a clean summary checkpoint',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '📦',
    actionType: 'immediate',
  },
  {
    command: '/clear',
    label: 'Clear Memory',
    description: 'Reset conversational context and start afresh',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '🧹',
    actionType: 'immediate',
  },
  {
    command: '/help',
    label: 'Antigravity Guide',
    description: 'Browse Antigravity skills, SDK methods, and slash command reference',
    category: 'agent',
    agentIds: ['antigravity'],
    icon: '❓',
    actionType: 'insert',
  },
];

export const TERMINAL_UNIVERSAL_COMMANDS: SlashCommandItem[] = [
  {
    command: '/switch',
    label: 'Switch Engine / Model',
    description: 'Switch active agent (Claude, Codex, Antigravity) with context handoff',
    category: 'terminal',
    icon: '🔄',
    actionType: 'immediate',
  },
  {
    command: '/undo',
    label: 'Undo Last Turn',
    description: 'Revert the last user message and agent response',
    category: 'terminal',
    icon: '↩️',
    actionType: 'immediate',
  },
  {
    command: '/compact',
    label: 'Compact History',
    description: 'Compact conversation into a lean checkpoint to optimize token usage',
    category: 'terminal',
    icon: '📦',
    actionType: 'immediate',
  },
  {
    command: '/stop',
    label: 'Stop Agent / Turn',
    description: 'Stop active turn generation or park underlying subprocess to free RAM & CPU',
    category: 'terminal',
    icon: '⏹',
    actionType: 'immediate',
  },
  {
    command: '/auto',
    label: 'Toggle Auto-Approval',
    description: 'Toggle automatic approval for all tool and shell command requests',
    category: 'terminal',
    icon: '⚡',
    actionType: 'immediate',
  },
  {
    command: '/stats',
    label: 'Vendor Limits & Usage',
    description: 'View 5-hour & weekly token utilization, rate limit resets, and subscription status',
    category: 'terminal',
    icon: '💳',
    actionType: 'immediate',
  },
  {
    command: '/git',
    label: 'Git Status & Diff',
    description: 'Ask agent to inspect current repository git branch, status, and modified files',
    category: 'terminal',
    icon: '🌿',
    actionType: 'insert',
  },
];

/**
 * Get all available slash commands for a specific agent.
 * Combines agent-specific native commands with universal terminal session commands.
 */
export function getSlashCommandsForAgent(agentId?: string): SlashCommandItem[] {
  const normId = (agentId || '').toLowerCase();

  let agentCommands: SlashCommandItem[] = [];
  if (normId.includes('claude') || normId.includes('anthropic')) {
    agentCommands = CLAUDE_COMMANDS;
  } else if (normId.includes('codex') || normId.includes('openai')) {
    agentCommands = CODEX_COMMANDS;
  } else if (normId.includes('antigravity') || normId.includes('gemini') || normId.includes('google')) {
    agentCommands = ANTIGRAVITY_COMMANDS;
  } else {
    // Default / Mock agent
    agentCommands = [
      {
        command: '/compact',
        label: 'Compact Context',
        description: 'Compact earlier verbose turns into a clean summary checkpoint',
        category: 'agent',
        icon: '📦',
        actionType: 'immediate',
      },
      {
        command: '/clear',
        label: 'Clear Memory',
        description: 'Reset context window',
        category: 'agent',
        icon: '🧹',
        actionType: 'immediate',
      },
      {
        command: '/help',
        label: 'ACP Agent Reference',
        description: 'Show agent capabilities and supported tools',
        category: 'agent',
        icon: '❓',
        actionType: 'insert',
      },
    ];
  }

  // Filter out any duplicates from terminal commands that share the same command name
  const agentCommandNames = new Set(agentCommands.map((c) => c.command));
  const uniqueTerminalCommands = TERMINAL_UNIVERSAL_COMMANDS.filter((tc) => !agentCommandNames.has(tc.command));

  return [...agentCommands, ...uniqueTerminalCommands];
}

/**
 * Filter slash commands by user query (e.g. "/co", "rev", "undo")
 */
export function filterSlashCommands(commands: SlashCommandItem[], query: string): SlashCommandItem[] {
  const clean = query.trim().toLowerCase().replace(/^\//, '');
  if (!clean) return commands;

  return commands.filter((cmd) => {
    const cmdName = cmd.command.toLowerCase().replace(/^\//, '');
    const label = cmd.label.toLowerCase();
    const desc = cmd.description.toLowerCase();
    return cmdName.includes(clean) || label.includes(clean) || desc.includes(clean);
  });
}
